
services:
  web:
    image: php:8.1-apache # O la versión de PHP que uses
    container_name: tp_final_web
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80" # 👈 MAPEAMOS AL PUERTO 8080 PARA NO PISAR XAMPP
    extra_hosts:
      - "host.docker.internal:host-gateway" # 👈 LA MAGIA PARA VER TU MYSQL LOCAL

  # Prometheus: El motor que recolecta las métricas probar http://localhost:9090
  
  # 1. cAdvisor: Monitorización de contenedores (Acceso: http://localhost:8082)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg

  # 2. Prometheus: Base de datos de métricas (Acceso: http://localhost:9090)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # 3. Grafana: Interfaz visual de gráficos (Acceso: http://localhost:3000)
  # RECUERDA: En la web de Grafana, la URL de Prometheus debe ser http://prometheus:9090
    # 3. Grafana: Interfaz visual de gráficos (Acceso: http://localhost:3000)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      # ESTA LÍNEA INYECTA LA CONFIGURACIÓN CORRECTA DIRECTAMENTE:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # 4. MySQL Exporter: Conexión con tu base de datos XAMPP local
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "root:@(host.docker.internal:3306)/"
    ports:
      - "9104:9104"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
